import { Component, OnInit } from '@angular/core';
import { Router } from "@angular/router";

@Component({
  selector: 'app-courses-upcoming',
  templateUrl: './courses-upcoming.component.html',
  styleUrls: ['./courses-upcoming.component.css']
})
export class CoursesUpcomingComponent implements OnInit {

  constructor(private router: Router) { }

  navigate() {
    this.router.navigate(["homepage-faculty"]);
  }

  courses: any[] = [
    {
      "CRN": 22272,
      "CRSE": "4220",
      "TITLE": "Advanced Data Analytics",
      "SECT": 1,
      "DAYS": "MW",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "B2100",
      "PER": 8,
      "CRDTS": 3,
      "LASTNAME": "Gunay",
      "FIRSTNAME": "Cengiz"
    },
    {
      "CRN": 22166,
      "CRSE": "4260",
      "TITLE": "Software Testing and QA",
      "SECT": 3,
      "DAYS": "F",
      "START": 1400,
      "END": 1645,
      "CLASSROOM": "A1520",
      "PER": 10,
      "CRDTS": 3,
      "LASTNAME": "Shin",
      "FIRSTNAME": "Hyun"
    },
    {
      "CRN": 20421,
      "CRSE": "1001",
      "TITLE": "Intro to Computing-Hybrid",
      "SECT": 24,
      "DAYS": "MW",
      "START": 1700,
      "END": 1815,
      "CLASSROOM": "A1710",
      "PER": 9,
      "CRDTS": 4,
      "LASTNAME": "Kurkovsky",
      "FIRSTNAME": "Anatoly"
    },
    {
      "CRN": 20425,
      "CRSE": "1001",
      "TITLE": "Intro to Computing-Hybrid",
      "SECT": 30,
      "DAYS": "T",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "B1100",
      "PER": 20,
      "CRDTS": 4,
      "LASTNAME": "Tran",
      "FIRSTNAME": "Andy"
    },
    {
      "CRN": 20736,
      "CRSE": "1001",
      "TITLE": "Intro. to Computing-Hybrid",
      "SECT": 50,
      "DAYS": "S",
      "START": 1100,
      "END": 1345,
      "CLASSROOM": "C2130",
      "PER": 23,
      "CRDTS": 4,
      "LASTNAME": "Tran",
      "FIRSTNAME": "Andy"
    },
    {
      "CRN": 20429,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 37,
      "DAYS": "MW",
      "START": 1400,
      "END": 1545,
      "CLASSROOM": "C1125",
      "PER": 7,
      "CRDTS": 4,
      "LASTNAME": "Tran",
      "FIRSTNAME": "Binh"
    },
    {
      "CRN": 20414,
      "CRSE": "1001",
      "TITLE": "Intro to Computing-Hybrid",
      "SECT": 13,
      "DAYS": "TR",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "B1200",
      "PER": 17,
      "CRDTS": 4,
      "LASTNAME": "Tran",
      "FIRSTNAME": "Binh"
    },
    {
      "CRN": 20740,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 55,
      "DAYS": "MW",
      "START": 1400,
      "END": 1545,
      "CLASSROOM": "A1930",
      "PER": 7,
      "CRDTS": 4,
      "LASTNAME": "Soares",
      "FIRSTNAME": "Carlos"
    },
    {
      "CRN": 21703,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 82,
      "DAYS": "TR",
      "START": 800,
      "END": 945,
      "CLASSROOM": "C2125",
      "PER": 14,
      "CRDTS": 4,
      "LASTNAME": "Richardson",
      "FIRSTNAME": "Carna"
    },
    {
      "CRN": 21702,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 81,
      "DAYS": "MW",
      "START": 1400,
      "END": 1545,
      "CLASSROOM": "C2125",
      "PER": 7,
      "CRDTS": 4,
      "LASTNAME": "Long",
      "FIRSTNAME": "Cherie"
    },
    {
      "CRN": 22164,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 2,
      "DAYS": "MWF",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "A1910",
      "PER": 5,
      "CRDTS": 4,
      "LASTNAME": "Robertson",
      "FIRSTNAME": "Cindy"
    },
    {
      "CRN": 20410,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 6,
      "DAYS": "MW",
      "START": 1600,
      "END": 1745,
      "CLASSROOM": "C2125",
      "PER": 8,
      "CRDTS": 4,
      "LASTNAME": "Hagler",
      "FIRSTNAME": "Dameon"
    },
    {
      "CRN": 20423,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 28,
      "DAYS": "TR",
      "START": 1200,
      "END": 1345,
      "CLASSROOM": "A1930",
      "PER": 17,
      "CRDTS": 4,
      "LASTNAME": "Knight",
      "FIRSTNAME": "David"
    },
    {
      "CRN": 20430,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 43,
      "DAYS": "TR",
      "START": 1000,
      "END": 1145,
      "CLASSROOM": "C1125",
      "PER": 15,
      "CRDTS": 4,
      "LASTNAME": "Knight",
      "FIRSTNAME": "David"
    },
    {
      "CRN": 20411,
      "CRSE": "1001",
      "TITLE": "Intro to Computing-Hybrid",
      "SECT": 8,
      "DAYS": "M",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "B1200",
      "PER": 11,
      "CRDTS": 4,
      "LASTNAME": "Oliver",
      "FIRSTNAME": "DeJarvis"
    },
    {
      "CRN": 20432,
      "CRSE": "1001",
      "TITLE": "Intro. to Computing-Hybrid",
      "SECT": 45,
      "DAYS": "TR",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "C1125",
      "PER": 18,
      "CRDTS": 4,
      "LASTNAME": "Brannock",
      "FIRSTNAME": "Evelyn"
    },
    {
      "CRN": 20417,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 19,
      "DAYS": "MWF",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "A1910",
      "PER": 4,
      "CRDTS": 4,
      "LASTNAME": "Choi",
      "FIRSTNAME": "Hongsik"
    },
    {
      "CRN": 20418,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 20,
      "DAYS": "MWF",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "C2100",
      "PER": 5,
      "CRDTS": 4,
      "LASTNAME": "Choi",
      "FIRSTNAME": "Hongsik"
    },
    {
      "CRN": 20426,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 33,
      "DAYS": "MWF",
      "START": 800,
      "END": 915,
      "CLASSROOM": "C1125",
      "PER": 1,
      "CRDTS": 4,
      "LASTNAME": "Hardy",
      "FIRSTNAME": "James"
    },
    {
      "CRN": 20427,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 34,
      "DAYS": "MWF",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "C1125",
      "PER": 2,
      "CRDTS": 4,
      "LASTNAME": "Hardy",
      "FIRSTNAME": "James"
    },
    {
      "CRN": 20412,
      "CRSE": "1001",
      "TITLE": "Intro to Computing-Hybrid",
      "SECT": 11,
      "DAYS": "TR",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "B1200",
      "PER": 15,
      "CRDTS": 4,
      "LASTNAME": "Kakish",
      "FIRSTNAME": "Kamal"
    },
    {
      "CRN": 20413,
      "CRSE": "1001",
      "TITLE": "Intro to Computing-Hybrid",
      "SECT": 12,
      "DAYS": "TR",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "B1200",
      "PER": 16,
      "CRDTS": 4,
      "LASTNAME": "Kakish",
      "FIRSTNAME": "Kamal"
    },
    {
      "CRN": 20433,
      "CRSE": "1001",
      "TITLE": "Intro. to Computing-Hybrid",
      "SECT": 46,
      "DAYS": "TR",
      "START": 1700,
      "END": 1815,
      "CLASSROOM": "C1125",
      "PER": 19,
      "CRDTS": 4,
      "LASTNAME": "Kakish",
      "FIRSTNAME": "Kamal"
    },
    {
      "CRN": 20733,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 15,
      "DAYS": "T",
      "START": 1830,
      "END": 2200,
      "CLASSROOM": "B1200",
      "PER": 20,
      "CRDTS": 4,
      "LASTNAME": "Benson",
      "FIRSTNAME": "Karen"
    },
    {
      "CRN": 20734,
      "CRSE": "1001",
      "TITLE": "Intro to Computing-Hybrid",
      "SECT": 23,
      "DAYS": "F",
      "START": 1400,
      "END": 1630,
      "CLASSROOM": "C1125",
      "PER": 10,
      "CRDTS": 4,
      "LASTNAME": "Benson",
      "FIRSTNAME": "Karen"
    },
    {
      "CRN": 20406,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 1,
      "DAYS": "MWF",
      "START": 800,
      "END": 915,
      "CLASSROOM": "B1200",
      "PER": 1,
      "CRDTS": 4,
      "LASTNAME": "Andrews",
      "FIRSTNAME": "Kauvon"
    },
    {
      "CRN": 20422,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 27,
      "DAYS": "TR",
      "START": 800,
      "END": 945,
      "CLASSROOM": "C1125",
      "PER": 14,
      "CRDTS": 4,
      "LASTNAME": "Andrews",
      "FIRSTNAME": "Kauvon"
    },
    {
      "CRN": 21178,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 73,
      "DAYS": "MWF",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "A1710",
      "PER": 4,
      "CRDTS": 4,
      "LASTNAME": "Wiggins",
      "FIRSTNAME": "Kimberly"
    },
    {
      "CRN": 21179,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 78,
      "DAYS": "MWF",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "A1930",
      "PER": 5,
      "CRDTS": 4,
      "LASTNAME": "Wiggins",
      "FIRSTNAME": "Kimberly"
    },
    {
      "CRN": 20419,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 21,
      "DAYS": "W",
      "START": 1830,
      "END": 2200,
      "CLASSROOM": "C1125",
      "PER": 12,
      "CRDTS": 4,
      "LASTNAME": "Bonsu",
      "FIRSTNAME": "Kwadwo"
    },
    {
      "CRN": 22165,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 7,
      "DAYS": "TR",
      "START": 1530,
      "END": 1715,
      "CLASSROOM": "C2125",
      "PER": 18,
      "CRDTS": 4,
      "LASTNAME": "Jonassen",
      "FIRSTNAME": "Lorraine"
    },
    {
      "CRN": 21177,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 72,
      "DAYS": "TR",
      "START": 1000,
      "END": 1145,
      "CLASSROOM": "B1100",
      "PER": 15,
      "CRDTS": 4,
      "LASTNAME": "Banerjee",
      "FIRSTNAME": "Madhushri"
    },
    {
      "CRN": 21174,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 68,
      "DAYS": "MWF",
      "START": 800,
      "END": 915,
      "CLASSROOM": "C2125",
      "PER": 1,
      "CRDTS": 4,
      "LASTNAME": "Nasir",
      "FIRSTNAME": "Manal"
    },
    {
      "CRN": 21701,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 79,
      "DAYS": "MWF",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "C2125",
      "PER": 2,
      "CRDTS": 4,
      "LASTNAME": "Nasir",
      "FIRSTNAME": "Manal"
    },
    {
      "CRN": 21399,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 63,
      "DAYS": "M",
      "START": 1830,
      "END": 2200,
      "CLASSROOM": "C2130",
      "PER": 11,
      "CRDTS": 4,
      "LASTNAME": "Fryling",
      "FIRSTNAME": "Margo"
    },
    {
      "CRN": 20735,
      "CRSE": "1001",
      "TITLE": "Intro to Computing-Hybrid",
      "SECT": 25,
      "DAYS": "W",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "A1910",
      "PER": 12,
      "CRDTS": 4,
      "LASTNAME": "Fryling",
      "FIRSTNAME": "Margo"
    },
    {
      "CRN": 20741,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 62,
      "DAYS": "TR",
      "START": 1200,
      "END": 1345,
      "CLASSROOM": "A1910",
      "PER": 17,
      "CRDTS": 4,
      "LASTNAME": "Abu Halwaeh",
      "FIRSTNAME": "Nael"
    },
    {
      "CRN": 20739,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 54,
      "DAYS": "MWF",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "A1710",
      "PER": 5,
      "CRDTS": 4,
      "LASTNAME": "Abu-Halaweh",
      "FIRSTNAME": "Nael"
    },
    {
      "CRN": 20415,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 16,
      "DAYS": "MWF",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "A1710",
      "PER": 8,
      "CRDTS": 4,
      "LASTNAME": "Nicklas",
      "FIRSTNAME": "Richard"
    },
    {
      "CRN": 20409,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 5,
      "DAYS": "MW",
      "START": 1400,
      "END": 1545,
      "CLASSROOM": "A1910",
      "PER": 7,
      "CRDTS": 4,
      "LASTNAME": "Kopinski",
      "FIRSTNAME": "Sean"
    },
    {
      "CRN": 20420,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 22,
      "DAYS": "MW",
      "START": 1600,
      "END": 1745,
      "CLASSROOM": "C1125",
      "PER": 8,
      "CRDTS": 4,
      "LASTNAME": "Kopinski",
      "FIRSTNAME": "Sean"
    },
    {
      "CRN": 21116,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 14,
      "DAYS": "TR",
      "START": 1530,
      "END": 1715,
      "CLASSROOM": "B1200",
      "PER": 18,
      "CRDTS": 4,
      "LASTNAME": "Smith",
      "FIRSTNAME": "Stella"
    },
    {
      "CRN": 21704,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 83,
      "DAYS": "TR",
      "START": 1000,
      "END": 1145,
      "CLASSROOM": "C2125",
      "PER": 16,
      "CRDTS": 4,
      "LASTNAME": "Smith",
      "FIRSTNAME": "Stella"
    },
    {
      "CRN": 21176,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 70,
      "DAYS": "MW",
      "START": 1530,
      "END": 1715,
      "CLASSROOM": "C2100",
      "PER": 8,
      "CRDTS": 4,
      "LASTNAME": "Smith",
      "FIRSTNAME": "Stella"
    },
    {
      "CRN": 20407,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 3,
      "DAYS": "MWF",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "B1200",
      "PER": 4,
      "CRDTS": 4,
      "LASTNAME": "Ahmed",
      "FIRSTNAME": "Syed"
    },
    {
      "CRN": 20408,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 4,
      "DAYS": "MWF",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "B1200",
      "PER": 5,
      "CRDTS": 4,
      "LASTNAME": "Ahmed",
      "FIRSTNAME": "Syed"
    },
    {
      "CRN": 20416,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 17,
      "DAYS": "MWF",
      "START": 800,
      "END": 915,
      "CLASSROOM": "A1930",
      "PER": 1,
      "CRDTS": 4,
      "LASTNAME": "Khokhar",
      "FIRSTNAME": "Umar"
    },
    {
      "CRN": 21397,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 51,
      "DAYS": "MWF",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "C2130",
      "PER": 2,
      "CRDTS": 4,
      "LASTNAME": "Khokhar",
      "FIRSTNAME": "Umar"
    },
    {
      "CRN": 20431,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 44,
      "DAYS": "TR",
      "START": 1200,
      "END": 1345,
      "CLASSROOM": "C1125",
      "PER": 17,
      "CRDTS": 4,
      "LASTNAME": "Liu",
      "FIRSTNAME": "Wei"
    },
    {
      "CRN": 20424,
      "CRSE": "1001",
      "TITLE": "Intro to Computing-Hybrid",
      "SECT": 29,
      "DAYS": "TR",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "A1910",
      "PER": 18,
      "CRDTS": 4,
      "LASTNAME": "Liu",
      "FIRSTNAME": "Wei"
    },
    {
      "CRN": 20737,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 52,
      "DAYS": "MWF",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "A1930",
      "PER": 2,
      "CRDTS": 4,
      "LASTNAME": "Xu",
      "FIRSTNAME": "Xin"
    },
    {
      "CRN": 20428,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 36,
      "DAYS": "MWF",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "C1125",
      "PER": 5,
      "CRDTS": 4,
      "LASTNAME": "Ding",
      "FIRSTNAME": "Yan"
    },
    {
      "CRN": 21395,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 26,
      "DAYS": "MWF",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "B1100",
      "PER": 4,
      "CRDTS": 4,
      "LASTNAME": "Ding",
      "FIRSTNAME": "Yan"
    },
    {
      "CRN": 21398,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 60,
      "DAYS": "MW",
      "START": 1400,
      "END": 1545,
      "CLASSROOM": "C2130",
      "PER": 7,
      "CRDTS": 4,
      "LASTNAME": "Ding",
      "FIRSTNAME": "Yan"
    },
    {
      "CRN": 20738,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 53,
      "DAYS": "MWF",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "C2100",
      "PER": 4,
      "CRDTS": 4,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 20852,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 35,
      "DAYS": "MWF",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "C1125",
      "PER": 4,
      "CRDTS": 4,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 20853,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 59,
      "DAYS": "MWF",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "B1100",
      "PER": 5,
      "CRDTS": 4,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 21017,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 66,
      "DAYS": "MWF",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "A1710",
      "PER": 2,
      "CRDTS": 4,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 21175,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 69,
      "DAYS": "MWF",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "C2130",
      "PER": 5,
      "CRDTS": 4,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 21396,
      "CRSE": "1001",
      "TITLE": "Intro to Computing",
      "SECT": 42,
      "DAYS": "MWF",
      "START": 800,
      "END": 915,
      "CLASSROOM": "C2130",
      "PER": 1,
      "CRDTS": 4,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 20854,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 23,
      "DAYS": "F",
      "START": 1400,
      "END": 1730,
      "CLASSROOM": "B1750",
      "PER": 10,
      "CRDTS": 4,
      "LASTNAME": "Heinz",
      "FIRSTNAME": "Adrian"
    },
    {
      "CRN": 20749,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 27,
      "DAYS": "TR",
      "START": 1000,
      "END": 1145,
      "CLASSROOM": "B1750",
      "PER": 15,
      "CRDTS": 4,
      "LASTNAME": "Shehab",
      "FIRSTNAME": "Amr"
    },
    {
      "CRN": 20750,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 28,
      "DAYS": "TR",
      "START": 1200,
      "END": 1345,
      "CLASSROOM": "B1750",
      "PER": 17,
      "CRDTS": 4,
      "LASTNAME": "Shehab",
      "FIRSTNAME": "Amr"
    },
    {
      "CRN": 21813,
      "CRSE": "2110",
      "TITLE": "Digital Media-Hybrid",
      "SECT": 39,
      "DAYS": "TR",
      "START": 1700,
      "END": 1815,
      "CLASSROOM": "A1450",
      "PER": 19,
      "CRDTS": 4,
      "LASTNAME": "Kwon",
      "FIRSTNAME": "Bongkyoung"
    },
    {
      "CRN": 20743,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 18,
      "DAYS": "MWF",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "B1750",
      "PER": 2,
      "CRDTS": 4,
      "LASTNAME": "Long",
      "FIRSTNAME": "Cherie"
    },
    {
      "CRN": 20435,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 2,
      "DAYS": "MWF",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "A1450",
      "PER": 2,
      "CRDTS": 4,
      "LASTNAME": "Robertson",
      "FIRSTNAME": "Cindy"
    },
    {
      "CRN": 20436,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 3,
      "DAYS": "MWF",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "A1450",
      "PER": 4,
      "CRDTS": 4,
      "LASTNAME": "Robertson",
      "FIRSTNAME": "Cindy"
    },
    {
      "CRN": 20751,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 31,
      "DAYS": "T",
      "START": 1830,
      "END": 2200,
      "CLASSROOM": "B1750",
      "PER": 20,
      "CRDTS": 4,
      "LASTNAME": "Jackson",
      "FIRSTNAME": "Jack"
    },
    {
      "CRN": 21998,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 9,
      "DAYS": "R",
      "START": 1830,
      "END": 2200,
      "CLASSROOM": "B1750",
      "PER": 21,
      "CRDTS": 4,
      "LASTNAME": "Jackson",
      "FIRSTNAME": "Jack"
    },
    {
      "CRN": 20434,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 1,
      "DAYS": "MWF",
      "START": 800,
      "END": 915,
      "CLASSROOM": "A1450",
      "PER": 1,
      "CRDTS": 4,
      "LASTNAME": "Streator",
      "FIRSTNAME": "Joycelyn"
    },
    {
      "CRN": 20441,
      "CRSE": "2110",
      "TITLE": "Digital Media-Hybrid",
      "SECT": 8,
      "DAYS": "M",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "A1450",
      "PER": 11,
      "CRDTS": 4,
      "LASTNAME": "Zinn",
      "FIRSTNAME": "JP"
    },
    {
      "CRN": 20746,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 22,
      "DAYS": "MW",
      "START": 1600,
      "END": 1745,
      "CLASSROOM": "B1750",
      "PER": 8,
      "CRDTS": 4,
      "LASTNAME": "Chen",
      "FIRSTNAME": "Kairui"
    },
    {
      "CRN": 21012,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 33,
      "DAYS": "MW",
      "START": 1400,
      "END": 1545,
      "CLASSROOM": "B1750",
      "PER": 7,
      "CRDTS": 4,
      "LASTNAME": "Chen",
      "FIRSTNAME": "Kairui"
    },
    {
      "CRN": 20856,
      "CRSE": "2110",
      "TITLE": "Digital Media-Hybrid",
      "SECT": 29,
      "DAYS": "S",
      "START": 800,
      "END": 1045,
      "CLASSROOM": "B1750",
      "PER": 22,
      "CRDTS": 4,
      "LASTNAME": "McGuffie",
      "FIRSTNAME": "Raymond"
    },
    {
      "CRN": 21064,
      "CRSE": "2110",
      "TITLE": "Digital Media-Hybrid",
      "SECT": 37,
      "DAYS": "S",
      "START": 1100,
      "END": 1345,
      "CLASSROOM": "A1450",
      "PER": 23,
      "CRDTS": 4,
      "LASTNAME": "McGuffie",
      "FIRSTNAME": "Raymond"
    },
    {
      "CRN": 20444,
      "CRSE": "2110",
      "TITLE": "Digital Media-Hybrid",
      "SECT": 13,
      "DAYS": "TR",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "A1450",
      "PER": 18,
      "CRDTS": 4,
      "LASTNAME": "Lai",
      "FIRSTNAME": "Shuhua"
    },
    {
      "CRN": 20742,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 16,
      "DAYS": "R",
      "START": 1830,
      "END": 2200,
      "CLASSROOM": "A1450",
      "PER": 21,
      "CRDTS": 4,
      "LASTNAME": "Dumas",
      "FIRSTNAME": "Tony"
    },
    {
      "CRN": 20445,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 15,
      "DAYS": "T",
      "START": 1830,
      "END": 2200,
      "CLASSROOM": "A1450",
      "PER": 20,
      "CRDTS": 4,
      "LASTNAME": "Biel",
      "FIRSTNAME": "Walter"
    },
    {
      "CRN": 20747,
      "CRSE": "2110",
      "TITLE": "Digital Media-Hybrid",
      "SECT": 25,
      "DAYS": "W",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "B1750",
      "PER": 12,
      "CRDTS": 4,
      "LASTNAME": "Biel",
      "FIRSTNAME": "Walter"
    },
    {
      "CRN": 20440,
      "CRSE": "2110",
      "TITLE": "Digital Media-Hybrid",
      "SECT": 7,
      "DAYS": "F",
      "START": 1400,
      "END": 1630,
      "CLASSROOM": "A1450",
      "PER": 10,
      "CRDTS": 4,
      "LASTNAME": "Mao",
      "FIRSTNAME": "Weidong"
    },
    {
      "CRN": 20857,
      "CRSE": "2110",
      "TITLE": "Digital Media-Hybrid",
      "SECT": 30,
      "DAYS": "TR",
      "START": 1700,
      "END": 1815,
      "CLASSROOM": "B1750",
      "PER": 19,
      "CRDTS": 4,
      "LASTNAME": "Mao",
      "FIRSTNAME": "Weidong"
    },
    {
      "CRN": 20437,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 4,
      "DAYS": "MWF",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "A1450",
      "PER": 5,
      "CRDTS": 4,
      "LASTNAME": "Xu",
      "FIRSTNAME": "Xin"
    },
    {
      "CRN": 20442,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 11,
      "DAYS": "TR",
      "START": 1000,
      "END": 1145,
      "CLASSROOM": "A1450",
      "PER": 15,
      "CRDTS": 4,
      "LASTNAME": "Xu",
      "FIRSTNAME": "Xin"
    },
    {
      "CRN": 20438,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 5,
      "DAYS": "MW",
      "START": 1400,
      "END": 1545,
      "CLASSROOM": "A1450",
      "PER": 7,
      "CRDTS": 4,
      "LASTNAME": "Xu",
      "FIRSTNAME": "Yaquan"
    },
    {
      "CRN": 20439,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 6,
      "DAYS": "MW",
      "START": 1600,
      "END": 1745,
      "CLASSROOM": "A1450",
      "PER": 8,
      "CRDTS": 4,
      "LASTNAME": "Xu",
      "FIRSTNAME": "Yaquan"
    },
    {
      "CRN": 20745,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 20,
      "DAYS": "MWF",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "B1750",
      "PER": 5,
      "CRDTS": 4,
      "LASTNAME": "Ding",
      "FIRSTNAME": "Yi"
    },
    {
      "CRN": 20855,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 24,
      "DAYS": "M",
      "START": 1830,
      "END": 2200,
      "CLASSROOM": "B1750",
      "PER": 11,
      "CRDTS": 4,
      "LASTNAME": "Lin",
      "FIRSTNAME": "Yu-Hsiu"
    },
    {
      "CRN": 21812,
      "CRSE": "2110",
      "TITLE": "Digital Media-Hybrid",
      "SECT": 38,
      "DAYS": "W",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "A1450",
      "PER": 12,
      "CRDTS": 4,
      "LASTNAME": "Lin",
      "FIRSTNAME": "Yu-Hsiu"
    },
    {
      "CRN": 20443,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 12,
      "DAYS": "TR",
      "START": 1200,
      "END": 1345,
      "CLASSROOM": "A1450",
      "PER": 17,
      "CRDTS": 4,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 20744,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 19,
      "DAYS": "MWF",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "B1750",
      "PER": 4,
      "CRDTS": 4,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 20748,
      "CRSE": "2110",
      "TITLE": "Digital Media",
      "SECT": 26,
      "DAYS": "TR",
      "START": 800,
      "END": 945,
      "CLASSROOM": "B1750",
      "PER": 14,
      "CRDTS": 4,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 21400,
      "CRSE": "2110",
      "TITLE": "Digital Media-Hybrid",
      "SECT": 10,
      "DAYS": "TR",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "B1750",
      "PER": 18,
      "CRDTS": 4,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 22014,
      "CRSE": "2110H",
      "TITLE": "Digital Media-Hybrid Honors",
      "SECT": 1,
      "DAYS": "TR",
      "START": 800,
      "END": 915,
      "CLASSROOM": "C2100",
      "PER": 14,
      "CRDTS": 4,
      "LASTNAME": "Abraham",
      "FIRSTNAME": "Sherly"
    },
    {
      "CRN": 22015,
      "CRSE": "2110H",
      "TITLE": "Digital Media-Hybrid Honors",
      "SECT": 2,
      "DAYS": "TR",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "C2100",
      "PER": 18,
      "CRDTS": 4,
      "LASTNAME": "Abraham",
      "FIRSTNAME": "Sherly"
    },
    {
      "CRN": 20446,
      "CRSE": "2120",
      "TITLE": "Intro to Programming",
      "SECT": 1,
      "DAYS": "MWF",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "B1100",
      "PER": 2,
      "CRDTS": 4,
      "LASTNAME": "Soares",
      "FIRSTNAME": "Carlos"
    },
    {
      "CRN": 21402,
      "CRSE": "2120",
      "TITLE": "Intro to Programming",
      "SECT": 15,
      "DAYS": "MWF",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "C2130",
      "PER": 4,
      "CRDTS": 4,
      "LASTNAME": "Soares",
      "FIRSTNAME": "Carlos"
    },
    {
      "CRN": 22001,
      "CRSE": "2120",
      "TITLE": "Intro to Programming",
      "SECT": 12,
      "DAYS": "MWF",
      "START": 800,
      "END": 915,
      "CLASSROOM": "C2100",
      "PER": 1,
      "CRDTS": 4,
      "LASTNAME": "Soares",
      "FIRSTNAME": "Carlos"
    },
    {
      "CRN": 21065,
      "CRSE": "2120",
      "TITLE": "Intro to Programming",
      "SECT": 8,
      "DAYS": "TR",
      "START": 1000,
      "END": 1145,
      "CLASSROOM": "A1910",
      "PER": 15,
      "CRDTS": 4,
      "LASTNAME": "Iken",
      "FIRSTNAME": "Mark"
    },
    {
      "CRN": 21066,
      "CRSE": "2120",
      "TITLE": "Intro to Programming",
      "SECT": 9,
      "DAYS": "TR",
      "START": 800,
      "END": 945,
      "CLASSROOM": "A1910",
      "PER": 14,
      "CRDTS": 4,
      "LASTNAME": "Iken",
      "FIRSTNAME": "Mark"
    },
    {
      "CRN": 21999,
      "CRSE": "2120",
      "TITLE": "Intro to Programming",
      "SECT": 5,
      "DAYS": "TR",
      "START": 1200,
      "END": 1345,
      "CLASSROOM": "C2130",
      "PER": 17,
      "CRDTS": 4,
      "LASTNAME": "Iken",
      "FIRSTNAME": "Mark"
    },
    {
      "CRN": 20448,
      "CRSE": "2120",
      "TITLE": "Intro to Programming",
      "SECT": 3,
      "DAYS": "MW",
      "START": 1830,
      "END": 2015,
      "CLASSROOM": "B1100",
      "PER": 11,
      "CRDTS": 4,
      "LASTNAME": "Siva",
      "FIRSTNAME": "Sebastien"
    },
    {
      "CRN": 20449,
      "CRSE": "2120",
      "TITLE": "Intro to Programming",
      "SECT": 4,
      "DAYS": "MW",
      "START": 1600,
      "END": 1745,
      "CLASSROOM": "A1910",
      "PER": 8,
      "CRDTS": 4,
      "LASTNAME": "Siva",
      "FIRSTNAME": "Sebastien"
    },
    {
      "CRN": 21067,
      "CRSE": "2120",
      "TITLE": "Intro to Programming",
      "SECT": 10,
      "DAYS": "MW",
      "START": 1400,
      "END": 1545,
      "CLASSROOM": "B1100",
      "PER": 7,
      "CRDTS": 4,
      "LASTNAME": "Siva",
      "FIRSTNAME": "Sebastien"
    },
    {
      "CRN": 21011,
      "CRSE": "2120",
      "TITLE": "Intro to Programming",
      "SECT": 7,
      "DAYS": "TR",
      "START": 1830,
      "END": 2015,
      "CLASSROOM": "A1930",
      "PER": 20,
      "CRDTS": 4,
      "LASTNAME": "Kasay ",
      "FIRSTNAME": "Valerie"
    },
    {
      "CRN": 21330,
      "CRSE": "2120",
      "TITLE": "Intro to Programming",
      "SECT": 11,
      "DAYS": "TR",
      "START": 1000,
      "END": 1145,
      "CLASSROOM": "C2130",
      "PER": 15,
      "CRDTS": 4,
      "LASTNAME": "Kasay",
      "FIRSTNAME": "Valerie"
    },
    {
      "CRN": 22000,
      "CRSE": "2120",
      "TITLE": "Intro to Programming",
      "SECT": 6,
      "DAYS": "MW",
      "START": 1600,
      "END": 1745,
      "CLASSROOM": "B1100",
      "PER": 8,
      "CRDTS": 4,
      "LASTNAME": "Kasay",
      "FIRSTNAME": "Valerie"
    },
    {
      "CRN": 20447,
      "CRSE": "2120",
      "TITLE": "Intro to Programming",
      "SECT": 2,
      "DAYS": "TR",
      "START": 800,
      "END": 945,
      "CLASSROOM": "A1930",
      "PER": 14,
      "CRDTS": 4,
      "LASTNAME": "Liu",
      "FIRSTNAME": "Wei"
    },
    {
      "CRN": 21401,
      "CRSE": "2120",
      "TITLE": "Intro to Programming",
      "SECT": 13,
      "DAYS": "TR",
      "START": 800,
      "END": 945,
      "CLASSROOM": "C2130",
      "PER": 14,
      "CRDTS": 4,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 20861,
      "CRSE": "2130",
      "TITLE": "Web Technologies",
      "SECT": 6,
      "DAYS": "T",
      "START": 1830,
      "END": 2200,
      "CLASSROOM": "C1125",
      "PER": 20,
      "CRDTS": 4,
      "LASTNAME": "Zinn",
      "FIRSTNAME": "JP"
    },
    {
      "CRN": 20862,
      "CRSE": "2130",
      "TITLE": "Web Technologies",
      "SECT": 7,
      "DAYS": "MWF",
      "START": 800,
      "END": 915,
      "CLASSROOM": "A1910",
      "PER": 1,
      "CRDTS": 4,
      "LASTNAME": "Murtaza",
      "FIRSTNAME": "Mirza"
    },
    {
      "CRN": 20860,
      "CRSE": "2130",
      "TITLE": "Web Technologies",
      "SECT": 4,
      "DAYS": "MWF",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "B1200",
      "PER": 2,
      "CRDTS": 4,
      "LASTNAME": "Xu",
      "FIRSTNAME": "Shuting"
    },
    {
      "CRN": 20863,
      "CRSE": "2130",
      "TITLE": "Web Technologies",
      "SECT": 10,
      "DAYS": "TR",
      "START": 1530,
      "END": 1715,
      "CLASSROOM": "A1930",
      "PER": 18,
      "CRDTS": 4,
      "LASTNAME": "Xu",
      "FIRSTNAME": "Shuting"
    },
    {
      "CRN": 21181,
      "CRSE": "2140",
      "TITLE": "Programming Fundamentals",
      "SECT": 2,
      "DAYS": "MW",
      "START": 1600,
      "END": 1745,
      "CLASSROOM": "A1750",
      "PER": 8,
      "CRDTS": 4,
      "LASTNAME": "Johnson",
      "FIRSTNAME": "Cynthia"
    },
    {
      "CRN": 22003,
      "CRSE": "2140",
      "TITLE": "Programming Fundamentals",
      "SECT": 12,
      "DAYS": "MW",
      "START": 1830,
      "END": 2015,
      "CLASSROOM": "C2125",
      "PER": 11,
      "CRDTS": 4,
      "LASTNAME": "Johnson",
      "FIRSTNAME": "Cynthia"
    },
    {
      "CRN": 21180,
      "CRSE": "2140",
      "TITLE": "Programming Fundamentals",
      "SECT": 1,
      "DAYS": "MWF",
      "START": 800,
      "END": 915,
      "CLASSROOM": "A1750",
      "PER": 1,
      "CRDTS": 4,
      "LASTNAME": "Park",
      "FIRSTNAME": "Hyesung"
    },
    {
      "CRN": 21187,
      "CRSE": "2140",
      "TITLE": "Programming Fundamentals",
      "SECT": 8,
      "DAYS": "MW",
      "START": 1400,
      "END": 1545,
      "CLASSROOM": "A1750",
      "PER": 7,
      "CRDTS": 4,
      "LASTNAME": "Park",
      "FIRSTNAME": "Hyesung"
    },
    {
      "CRN": 21186,
      "CRSE": "2140",
      "TITLE": "Programming Fundamentals",
      "SECT": 7,
      "DAYS": "MWF",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "A1750",
      "PER": 5,
      "CRDTS": 4,
      "LASTNAME": "Murtaza",
      "FIRSTNAME": "Mirza"
    },
    {
      "CRN": 22002,
      "CRSE": "2140",
      "TITLE": "Programming Fundamentals",
      "SECT": 9,
      "DAYS": "MWF",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "C2100",
      "PER": 2,
      "CRDTS": 4,
      "LASTNAME": "Murtaza",
      "FIRSTNAME": "Mirza"
    },
    {
      "CRN": 21404,
      "CRSE": "2140",
      "TITLE": "Programming Fundamentals",
      "SECT": 11,
      "DAYS": "TR",
      "START": 1530,
      "END": 1715,
      "CLASSROOM": "C2130",
      "PER": 18,
      "CRDTS": 4,
      "LASTNAME": "Abu-Halaweh",
      "FIRSTNAME": "Nael"
    },
    {
      "CRN": 21185,
      "CRSE": "2140",
      "TITLE": "Programming Fundamentals",
      "SECT": 6,
      "DAYS": "TR",
      "START": 1830,
      "END": 2015,
      "CLASSROOM": "A1710",
      "PER": 20,
      "CRDTS": 4,
      "LASTNAME": "Abu Halwaeh",
      "FIRSTNAME": "Nael"
    },
    {
      "CRN": 21183,
      "CRSE": "2140",
      "TITLE": "Programming Fundamentals",
      "SECT": 4,
      "DAYS": "TR",
      "START": 1000,
      "END": 1145,
      "CLASSROOM": "A1750",
      "PER": 15,
      "CRDTS": 4,
      "LASTNAME": "Dekhane",
      "FIRSTNAME": "Sonal"
    },
    {
      "CRN": 21184,
      "CRSE": "2140",
      "TITLE": "Programming Fundamentals",
      "SECT": 5,
      "DAYS": "TR",
      "START": 800,
      "END": 945,
      "CLASSROOM": "A1750",
      "PER": 14,
      "CRDTS": 4,
      "LASTNAME": "Dekhane",
      "FIRSTNAME": "Sonal"
    },
    {
      "CRN": 21403,
      "CRSE": "2140",
      "TITLE": "Programming Fundamentals",
      "SECT": 10,
      "DAYS": "TR",
      "START": 800,
      "END": 945,
      "CLASSROOM": "B1100",
      "PER": 14,
      "CRDTS": 4,
      "LASTNAME": "Jin",
      "FIRSTNAME": "Wei"
    },
    {
      "CRN": 21182,
      "CRSE": "2140",
      "TITLE": "Programming Fundamentals",
      "SECT": 3,
      "DAYS": "TR",
      "START": 1530,
      "END": 1715,
      "CLASSROOM": "A1710",
      "PER": 18,
      "CRDTS": 4,
      "LASTNAME": "Jin",
      "FIRSTNAME": "Wei"
    },
    {
      "CRN": 20858,
      "CRSE": "2150",
      "TITLE": "Intermediate Programming",
      "SECT": 4,
      "DAYS": "TR",
      "START": 1830,
      "END": 2015,
      "CLASSROOM": "C2130",
      "PER": 20,
      "CRDTS": 4,
      "LASTNAME": "Heinz",
      "FIRSTNAME": "Adrian"
    },
    {
      "CRN": 21188,
      "CRSE": "2150",
      "TITLE": "Intermediate Programming",
      "SECT": 6,
      "DAYS": "TR",
      "START": 1200,
      "END": 1345,
      "CLASSROOM": "A1750",
      "PER": 17,
      "CRDTS": 4,
      "LASTNAME": "Heinz",
      "FIRSTNAME": "Adrian"
    },
    {
      "CRN": 20450,
      "CRSE": "2150",
      "TITLE": "Intermediate Programming",
      "SECT": 2,
      "DAYS": "MWF",
      "START": 800,
      "END": 915,
      "CLASSROOM": "B1100",
      "PER": 1,
      "CRDTS": 4,
      "LASTNAME": "Pereira",
      "FIRSTNAME": "Anil"
    },
    {
      "CRN": 21405,
      "CRSE": "2150",
      "TITLE": "Intermediate Programming",
      "SECT": 7,
      "DAYS": "S",
      "START": 1100,
      "END": 1430,
      "CLASSROOM": "A1750",
      "PER": 23,
      "CRDTS": 4,
      "LASTNAME": "Kwon",
      "FIRSTNAME": "Bongkyoung"
    },
    {
      "CRN": 20752,
      "CRSE": "2150",
      "TITLE": "Intermediate Programming",
      "SECT": 1,
      "DAYS": "TR",
      "START": 1000,
      "END": 1145,
      "CLASSROOM": "A1930",
      "PER": 15,
      "CRDTS": 4,
      "LASTNAME": "Park",
      "FIRSTNAME": "Hyesung"
    },
    {
      "CRN": 20451,
      "CRSE": "2150",
      "TITLE": "Intermediate Programming",
      "SECT": 3,
      "DAYS": "TR",
      "START": 1530,
      "END": 1715,
      "CLASSROOM": "A1750",
      "PER": 18,
      "CRDTS": 4,
      "LASTNAME": "Price",
      "FIRSTNAME": "Richard"
    },
    {
      "CRN": 21103,
      "CRSE": "2150",
      "TITLE": "Intermediate Programming",
      "SECT": 5,
      "DAYS": "MWF",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "A1930",
      "PER": 4,
      "CRDTS": 4,
      "LASTNAME": "Im",
      "FIRSTNAME": "Tacksoo"
    },
    {
      "CRN": 21189,
      "CRSE": "2201",
      "TITLE": "Introduction to Info Systems",
      "SECT": 7,
      "DAYS": "M",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "A1910",
      "PER": 11,
      "CRDTS": 3,
      "LASTNAME": "Skinner",
      "FIRSTNAME": "Calvin"
    },
    {
      "CRN": 20753,
      "CRSE": "2201",
      "TITLE": "Introduction to Info Systems",
      "SECT": 2,
      "DAYS": "TR",
      "START": 1700,
      "END": 1815,
      "CLASSROOM": "C2100",
      "PER": 19,
      "CRDTS": 3,
      "LASTNAME": "Banerjee",
      "FIRSTNAME": "Madhushri"
    },
    {
      "CRN": 20754,
      "CRSE": "2201",
      "TITLE": "Introduction to Info Systems",
      "SECT": 3,
      "DAYS": "TR",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "B1100",
      "PER": 17,
      "CRDTS": 3,
      "LASTNAME": "Baerjee",
      "FIRSTNAME": "Madhushri"
    },
    {
      "CRN": 20864,
      "CRSE": "2201",
      "TITLE": "Introduction to Info Systems",
      "SECT": 4,
      "DAYS": "TR",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "B1100",
      "PER": 18,
      "CRDTS": 3,
      "LASTNAME": "Banerjee",
      "FIRSTNAME": "Madhushri"
    },
    {
      "CRN": 20859,
      "CRSE": "2201",
      "TITLE": "Introduction to Info Systems",
      "SECT": 1,
      "DAYS": "MW",
      "START": 1400,
      "END": 1515,
      "CLASSROOM": "B1200",
      "PER": 7,
      "CRDTS": 3,
      "LASTNAME": "Kasay",
      "FIRSTNAME": "Valerie"
    },
    {
      "CRN": 21106,
      "CRSE": "2201",
      "TITLE": "Introduction to Info Systems",
      "SECT": 6,
      "DAYS": "F",
      "START": 1400,
      "END": 1630,
      "CLASSROOM": "C2130",
      "PER": 10,
      "CRDTS": 3,
      "LASTNAME": "Ding",
      "FIRSTNAME": "Yi"
    },
    {
      "CRN": 21705,
      "CRSE": "2201",
      "TITLE": "Introduction to Info Systems",
      "SECT": 8,
      "DAYS": "MW",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "B1200",
      "PER": 8,
      "CRDTS": 3,
      "LASTNAME": "Ding",
      "FIRSTNAME": "YI"
    },
    {
      "CRN": 21019,
      "CRSE": "2500",
      "TITLE": "Intro to Undergrad Research",
      "SECT": 1,
      "DAYS": "F",
      "START": 700,
      "END": 750,
      "CLASSROOM": "A1140",
      "PER": 0,
      "CRDTS": 1,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 22007,
      "CRSE": "3100",
      "TITLE": "Introduction to Networks",
      "SECT": 6,
      "DAYS": "TR",
      "START": 800,
      "END": 915,
      "CLASSROOM": "B1950",
      "PER": 14,
      "CRDTS": 3,
      "LASTNAME": "Pereira",
      "FIRSTNAME": "Anil"
    },
    {
      "CRN": 20755,
      "CRSE": "3100",
      "TITLE": "Introduction to Networks",
      "SECT": 2,
      "DAYS": "MWF",
      "START": 1000,
      "END": 1050,
      "CLASSROOM": "B1950",
      "PER": 3,
      "CRDTS": 3,
      "LASTNAME": "Pereira",
      "FIRSTNAME": "Anil"
    },
    {
      "CRN": 20865,
      "CRSE": "3100",
      "TITLE": "Introduction to Networks",
      "SECT": 3,
      "DAYS": "TR",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "B2100",
      "PER": 18,
      "CRDTS": 3,
      "LASTNAME": "Tran",
      "FIRSTNAME": "Binh"
    },
    {
      "CRN": 21406,
      "CRSE": "3100",
      "TITLE": "Introduction to Networks",
      "SECT": 4,
      "DAYS": "MW",
      "START": 1700,
      "END": 1815,
      "CLASSROOM": "B1950",
      "PER": 9,
      "CRDTS": 3,
      "LASTNAME": "Tran",
      "FIRSTNAME": "Binh"
    },
    {
      "CRN": 20452,
      "CRSE": "3100",
      "TITLE": "Introduction to Networks",
      "SECT": 1,
      "DAYS": "R",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "B1950",
      "PER": 21,
      "CRDTS": 3,
      "LASTNAME": "Osunkoya",
      "FIRSTNAME": "Ola"
    },
    {
      "CRN": 21407,
      "CRSE": "3100",
      "TITLE": "Introduction to Networks",
      "SECT": 5,
      "DAYS": "S",
      "START": 800,
      "END": 1045,
      "CLASSROOM": "W1104",
      "PER": 22,
      "CRDTS": 3,
      "LASTNAME": "Osunkoya",
      "FIRSTNAME": "Ola"
    },
    {
      "CRN": 21408,
      "CRSE": "3150",
      "TITLE": "Advanced Programming",
      "SECT": 3,
      "DAYS": "MW",
      "START": 800,
      "END": 915,
      "CLASSROOM": "B2100",
      "PER": 1,
      "CRDTS": 3,
      "LASTNAME": "Doloc-Mihy",
      "FIRSTNAME": "Anca"
    },
    {
      "CRN": 20454,
      "CRSE": "3150",
      "TITLE": "Advanced Programming",
      "SECT": 1,
      "DAYS": "TR",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "B1950",
      "PER": 16,
      "CRDTS": 3,
      "LASTNAME": "Brannock",
      "FIRSTNAME": "Evelyn"
    },
    {
      "CRN": 20756,
      "CRSE": "3150",
      "TITLE": "Advanced Programming",
      "SECT": 2,
      "DAYS": "T",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "B1950",
      "PER": 20,
      "CRDTS": 3,
      "LASTNAME": "Jin",
      "FIRSTNAME": "Wei"
    },
    {
      "CRN": 22004,
      "CRSE": "3200",
      "TITLE": "Intro to Databases",
      "SECT": 6,
      "DAYS": "MW",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "A1120",
      "PER": 2,
      "CRDTS": 3,
      "LASTNAME": "Wang",
      "FIRSTNAME": "Cuilan"
    },
    {
      "CRN": 20453,
      "CRSE": "3200",
      "TITLE": "Intro to Databases",
      "SECT": 1,
      "DAYS": "MW",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "C2220",
      "PER": 8,
      "CRDTS": 3,
      "LASTNAME": "Choi",
      "FIRSTNAME": "Hongsik"
    },
    {
      "CRN": 20866,
      "CRSE": "3200",
      "TITLE": "Intro to Databases",
      "SECT": 3,
      "DAYS": "MW",
      "START": 1700,
      "END": 1815,
      "CLASSROOM": "W3201",
      "PER": 9,
      "CRDTS": 3,
      "LASTNAME": "Pollacia",
      "FIRSTNAME": "Lissa"
    },
    {
      "CRN": 21410,
      "CRSE": "3200",
      "TITLE": "Intro to Databases",
      "SECT": 5,
      "DAYS": "M",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "B2100",
      "PER": 11,
      "CRDTS": 3,
      "LASTNAME": "Hughes",
      "FIRSTNAME": "Norris"
    },
    {
      "CRN": 20757,
      "CRSE": "3200",
      "TITLE": "Intro to Databases",
      "SECT": 2,
      "DAYS": "TR",
      "START": 800,
      "END": 915,
      "CLASSROOM": "H2205",
      "PER": 14,
      "CRDTS": 3,
      "LASTNAME": "Lawson",
      "FIRSTNAME": "Victor"
    },
    {
      "CRN": 21409,
      "CRSE": "3200",
      "TITLE": "Intro to Databases",
      "SECT": 4,
      "DAYS": "TR",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "B2200",
      "PER": 18,
      "CRDTS": 3,
      "LASTNAME": "Lawson",
      "FIRSTNAME": "Victor"
    },
    {
      "CRN": 20455,
      "CRSE": "3300",
      "TITLE": "Information Security",
      "SECT": 1,
      "DAYS": "MW",
      "START": 1700,
      "END": 1815,
      "CLASSROOM": "W3147",
      "PER": 9,
      "CRDTS": 3,
      "LASTNAME": "Xu",
      "FIRSTNAME": "Shuting"
    },
    {
      "CRN": 21797,
      "CRSE": "3300",
      "TITLE": "Information Security",
      "SECT": 4,
      "DAYS": "MW",
      "START": 1400,
      "END": 1515,
      "CLASSROOM": "B2200",
      "PER": 7,
      "CRDTS": 3,
      "LASTNAME": "Khokhar",
      "FIRSTNAME": "Umar"
    },
    {
      "CRN": 21411,
      "CRSE": "3300",
      "TITLE": "Information Security",
      "SECT": 2,
      "DAYS": "TR",
      "START": 800,
      "END": 915,
      "CLASSROOM": "B2200",
      "PER": 14,
      "CRDTS": 3,
      "LASTNAME": "Khokhar",
      "FIRSTNAME": "Umar"
    },
    {
      "CRN": 20456,
      "CRSE": "3350",
      "TITLE": "Digital Commerce",
      "SECT": 1,
      "DAYS": "TR",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "B1950",
      "PER": 17,
      "CRDTS": 3,
      "LASTNAME": "Jonassen",
      "FIRSTNAME": "Lorraine"
    },
    {
      "CRN": 21412,
      "CRSE": "3350",
      "TITLE": "Digital Commerce",
      "SECT": 3,
      "DAYS": "MW",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "H2205",
      "PER": 8,
      "CRDTS": 3,
      "LASTNAME": "Mao",
      "FIRSTNAME": "Weidong"
    },
    {
      "CRN": 22005,
      "CRSE": "3350",
      "TITLE": "Digital Commerce",
      "SECT": 2,
      "DAYS": "W",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "W3201",
      "PER": 12,
      "CRDTS": 3,
      "LASTNAME": "Mao",
      "FIRSTNAME": "Weidong"
    },
    {
      "CRN": 21413,
      "CRSE": "3450",
      "TITLE": "Comp Graphics and Multimedia",
      "SECT": 1,
      "DAYS": "TR",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "B2200",
      "PER": 17,
      "CRDTS": 3,
      "LASTNAME": "Wang",
      "FIRSTNAME": "Cuilan"
    },
    {
      "CRN": 21706,
      "CRSE": "3450",
      "TITLE": "Comp Graphics and Multimedia",
      "SECT": 2,
      "DAYS": "TR",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "B2200",
      "PER": 16,
      "CRDTS": 3,
      "LASTNAME": "Wang ",
      "FIRSTNAME": "Cuilan"
    },
    {
      "CRN": 20758,
      "CRSE": "3600",
      "TITLE": "Operating Systems",
      "SECT": 1,
      "DAYS": "MW",
      "START": 800,
      "END": 915,
      "CLASSROOM": "W3201",
      "PER": 1,
      "CRDTS": 3,
      "LASTNAME": "Kurkovsky",
      "FIRSTNAME": "Anatoly"
    },
    {
      "CRN": 21707,
      "CRSE": "3600",
      "TITLE": "Operating Systems",
      "SECT": 2,
      "DAYS": "T",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "B2200",
      "PER": 20,
      "CRDTS": 3,
      "LASTNAME": "Kurkovsky",
      "FIRSTNAME": "Anatoly"
    },
    {
      "CRN": 20867,
      "CRSE": "3700",
      "TITLE": "Systems Analysis and Design",
      "SECT": 2,
      "DAYS": "MW",
      "START": 1400,
      "END": 1515,
      "CLASSROOM": "B1950",
      "PER": 7,
      "CRDTS": 3,
      "LASTNAME": "Johnson",
      "FIRSTNAME": "Cynthia"
    },
    {
      "CRN": 20457,
      "CRSE": "3700",
      "TITLE": "Systems Analysis and Design",
      "SECT": 1,
      "DAYS": "TR",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "B2100",
      "PER": 16,
      "CRDTS": 3,
      "LASTNAME": "Shin",
      "FIRSTNAME": "Hyun"
    },
    {
      "CRN": 21414,
      "CRSE": "3700",
      "TITLE": "Systems Analysis and Design",
      "SECT": 3,
      "DAYS": "TR",
      "START": 1700,
      "END": 1815,
      "CLASSROOM": "B2100",
      "PER": 19,
      "CRDTS": 3,
      "LASTNAME": "Shin",
      "FIRSTNAME": "Hyun"
    },
    {
      "CRN": 21540,
      "CRSE": "3700",
      "TITLE": "Systems Analysis/Design",
      "SECT": 4,
      "DAYS": "M",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "B1950",
      "PER": 11,
      "CRDTS": 3,
      "LASTNAME": "Nicklas",
      "FIRSTNAME": "Richard"
    },
    {
      "CRN": 20458,
      "CRSE": "3860",
      "TITLE": "Software Development I",
      "SECT": 1,
      "DAYS": "MW",
      "START": 1530,
      "END": 1715,
      "CLASSROOM": "A1520",
      "PER": 8,
      "CRDTS": 4,
      "LASTNAME": "Doloc Mihu",
      "FIRSTNAME": "Anca"
    },
    {
      "CRN": 21708,
      "CRSE": "3860",
      "TITLE": "Software Development I",
      "SECT": 2,
      "DAYS": "TR",
      "START": 1830,
      "END": 2015,
      "CLASSROOM": "B2100",
      "PER": 20,
      "CRDTS": 4,
      "LASTNAME": "Doloc Mihu",
      "FIRSTNAME": "Anca"
    },
    {
      "CRN": 20459,
      "CRSE": "3870",
      "TITLE": "Software Development II",
      "SECT": 1,
      "DAYS": "M",
      "START": 1830,
      "END": 2200,
      "CLASSROOM": "B2200",
      "PER": 11,
      "CRDTS": 4,
      "LASTNAME": "Gunay",
      "FIRSTNAME": "Cengiz"
    },
    {
      "CRN": 21709,
      "CRSE": "3870",
      "TITLE": "Software Development II",
      "SECT": 2,
      "DAYS": "MW",
      "START": 1100,
      "END": 1245,
      "CLASSROOM": "B1950",
      "PER": 4,
      "CRDTS": 4,
      "LASTNAME": "Gunay",
      "FIRSTNAME": "Cengiz"
    },
    {
      "CRN": 20460,
      "CRSE": "3900",
      "TITLE": "Professional Pract & Ethics",
      "SECT": 1,
      "DAYS": "MWF",
      "START": 1100,
      "END": 1150,
      "CLASSROOM": "B2100",
      "PER": 4,
      "CRDTS": 3,
      "LASTNAME": "Streator",
      "FIRSTNAME": "Joycelyn"
    },
    {
      "CRN": 20868,
      "CRSE": "3900",
      "TITLE": "Professional Pract & Ethics",
      "SECT": 3,
      "DAYS": "MWF",
      "START": 1300,
      "END": 1350,
      "CLASSROOM": "B2100",
      "PER": 6,
      "CRDTS": 3,
      "LASTNAME": "Streator",
      "FIRSTNAME": "Joycelyn"
    },
    {
      "CRN": 20759,
      "CRSE": "3900",
      "TITLE": "Professional Pract & Ethics",
      "SECT": 2,
      "DAYS": "TR",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "C1220",
      "PER": 15,
      "CRDTS": 3,
      "LASTNAME": "Jonassen",
      "FIRSTNAME": "Lorraine"
    },
    {
      "CRN": 21415,
      "CRSE": "3900",
      "TITLE": "Professional Pract & Ethics",
      "SECT": 4,
      "DAYS": "S",
      "START": 1100,
      "END": 1345,
      "CLASSROOM": "B1950",
      "PER": 23,
      "CRDTS": 3,
      "LASTNAME": "Nicklas",
      "FIRSTNAME": "Richard"
    },
    {
      "CRN": 21710,
      "CRSE": "4100",
      "TITLE": "Advanced Networks",
      "SECT": 1,
      "DAYS": "S",
      "START": 800,
      "END": 1045,
      "CLASSROOM": "B1950",
      "PER": 22,
      "CRDTS": 3,
      "LASTNAME": "Pereira",
      "FIRSTNAME": "Anil"
    },
    {
      "CRN": 21711,
      "CRSE": "4110",
      "TITLE": "Digital Media Capstone Project",
      "SECT": 1,
      "DAYS": "M",
      "START": 1830,
      "END": 2200,
      "CLASSROOM": "C1110",
      "PER": 11,
      "CRDTS": 4,
      "LASTNAME": "Long",
      "FIRSTNAME": "Cherie"
    },
    {
      "CRN": 22020,
      "CRSE": "4130",
      "TITLE": "Human Computer Interaction",
      "SECT": 1,
      "DAYS": "W",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "A1520",
      "PER": 12,
      "CRDTS": 3,
      "LASTNAME": "Chen",
      "FIRSTNAME": "Kairui"
    },
    {
      "CRN": 21416,
      "CRSE": "4150",
      "TITLE": "Enterprise Process Integration",
      "SECT": 1,
      "DAYS": "R",
      "START": 1830,
      "END": 2200,
      "CLASSROOM": "A1520",
      "PER": 21,
      "CRDTS": 4,
      "LASTNAME": "Ding",
      "FIRSTNAME": "Yi"
    },
    {
      "CRN": 20461,
      "CRSE": "4200",
      "TITLE": "Advanced Databases",
      "SECT": 1,
      "DAYS": "MWF",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "B1950",
      "PER": 8,
      "CRDTS": 4,
      "LASTNAME": "Pollacia",
      "FIRSTNAME": "Lissa"
    },
    {
      "CRN": 21712,
      "CRSE": "4200",
      "TITLE": "Advanced Databases",
      "SECT": 2,
      "DAYS": "S",
      "START": 1100,
      "END": 1430,
      "CLASSROOM": "B2100",
      "PER": 23,
      "CRDTS": 4,
      "LASTNAME": "Lawson",
      "FIRSTNAME": "Victor"
    },
    {
      "CRN": 21190,
      "CRSE": "4210",
      "TITLE": "Information Analytics",
      "SECT": 1,
      "DAYS": "T",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "A1750",
      "PER": 20,
      "CRDTS": 3,
      "LASTNAME": "Brannock",
      "FIRSTNAME": "Evelyn"
    },
    {
      "CRN": 21713,
      "CRSE": "4260",
      "TITLE": "Software Testing and QA",
      "SECT": 2,
      "DAYS": "W",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "B2200",
      "PER": 12,
      "CRDTS": 3,
      "LASTNAME": "Shin",
      "FIRSTNAME": "Hyun"
    },
    {
      "CRN": 20818,
      "CRSE": "4260",
      "TITLE": "Software Testing and QA",
      "SECT": 1,
      "DAYS": "MW",
      "START": 1530,
      "END": 1645,
      "CLASSROOM": "B2200",
      "PER": 8,
      "CRDTS": 3,
      "LASTNAME": "Im",
      "FIRSTNAME": "Tacksoo"
    },
    {
      "CRN": 21714,
      "CRSE": "4320",
      "TITLE": "Internet Security",
      "SECT": 1,
      "DAYS": "W",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "A1125",
      "PER": 12,
      "CRDTS": 3,
      "LASTNAME": "Ding",
      "FIRSTNAME": "Yan"
    },
    {
      "CRN": 21558,
      "CRSE": "4330",
      "TITLE": "System Administration",
      "SECT": 1,
      "DAYS": "MWF",
      "START": 1100,
      "END": 1215,
      "CLASSROOM": "W3201",
      "PER": 4,
      "CRDTS": 4,
      "LASTNAME": "Yang",
      "FIRSTNAME": "Sean"
    },
    {
      "CRN": 21715,
      "CRSE": "4330",
      "TITLE": "System Administration",
      "SECT": 2,
      "DAYS": "R",
      "START": 1830,
      "END": 2200,
      "CLASSROOM": "A1900",
      "PER": 21,
      "CRDTS": 4,
      "LASTNAME": "Yang",
      "FIRSTNAME": "Sean"
    },
    {
      "CRN": 21825,
      "CRSE": "4400",
      "TITLE": "Special Topics in Infor. Tech.",
      "SECT": 3,
      "DAYS": "F",
      "START": 1400,
      "END": 1645,
      "CLASSROOM": "A1320",
      "PER": 10,
      "CRDTS": 4,
      "LASTNAME": "Lawson",
      "FIRSTNAME": "Victor"
    },
    {
      "CRN": 21349,
      "CRSE": "4400",
      "TITLE": "Sp Topics in Info Tech",
      "SECT": 1,
      "DAYS": "W",
      "START": 1530,
      "END": 1715,
      "CLASSROOM": "H1102",
      "PER": 8,
      "CRDTS": 1,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 21821,
      "CRSE": "4400",
      "TITLE": "Special Topics in Infor. Tech.",
      "SECT": 2,
      "DAYS": "TR",
      "START": 700,
      "END": 750,
      "CLASSROOM": "A1520",
      "PER": 0,
      "CRDTS": 1,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 22044,
      "CRSE": "4400",
      "TITLE": "Special Topics in Infor. Tech.",
      "SECT": 4,
      "DAYS": "M",
      "START": 700,
      "END": 750,
      "CLASSROOM": "B1950",
      "PER": 0,
      "CRDTS": 1,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 22045,
      "CRSE": "4400",
      "TITLE": "Special Topics in Infor. Tech.",
      "SECT": 5,
      "DAYS": "TR",
      "START": 700,
      "END": 750,
      "CLASSROOM": "B1950",
      "PER": 0,
      "CRDTS": 1,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 21716,
      "CRSE": "4450",
      "TITLE": "Web Development",
      "SECT": 1,
      "DAYS": "MWF",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "B2100",
      "PER": 2,
      "CRDTS": 4,
      "LASTNAME": "Lai",
      "FIRSTNAME": "Shuhua"
    },
    {
      "CRN": 21717,
      "CRSE": "4450",
      "TITLE": "Web Development",
      "SECT": 2,
      "DAYS": "T",
      "START": 1830,
      "END": 2200,
      "CLASSROOM": "W1104",
      "PER": 20,
      "CRDTS": 4,
      "LASTNAME": "Lai",
      "FIRSTNAME": "Shuhua"
    },
    {
      "CRN": 20518,
      "CRSE": "4500",
      "TITLE": "Undergraduate Research Project",
      "SECT": 1,
      "DAYS": "S",
      "START": 700,
      "END": 750,
      "CLASSROOM": "A1150",
      "PER": 0,
      "CRDTS": 3,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 21718,
      "CRSE": "4550",
      "TITLE": "Mobile Application Development",
      "SECT": 2,
      "DAYS": "MW",
      "START": 1400,
      "END": 1515,
      "CLASSROOM": "C1130",
      "PER": 7,
      "CRDTS": 3,
      "LASTNAME": "Doloc Mihu",
      "FIRSTNAME": "Anca"
    },
    {
      "CRN": 21327,
      "CRSE": "4550",
      "TITLE": "Mobile Application Development",
      "SECT": 1,
      "DAYS": "TR",
      "START": 1700,
      "END": 1815,
      "CLASSROOM": "W3201",
      "PER": 19,
      "CRDTS": 3,
      "LASTNAME": "Lutz",
      "FIRSTNAME": "Robert"
    },
    {
      "CRN": 20993,
      "CRSE": "4650",
      "TITLE": "Game Development",
      "SECT": 1,
      "DAYS": "F",
      "START": 1400,
      "END": 1645,
      "CLASSROOM": "B2200",
      "PER": 10,
      "CRDTS": 3,
      "LASTNAME": "Siva",
      "FIRSTNAME": "Sebastien"
    },
    {
      "CRN": 21870,
      "CRSE": "4700",
      "TITLE": "Artificial Intelligence",
      "SECT": 1,
      "DAYS": "TR",
      "START": 930,
      "END": 1045,
      "CLASSROOM": "B1950",
      "PER": 15,
      "CRDTS": 3,
      "LASTNAME": "Lutz",
      "FIRSTNAME": "Robert"
    },
    {
      "CRN": 21088,
      "CRSE": "4750",
      "TITLE": "Enterprise Arch Design-Hybrid",
      "SECT": 1,
      "DAYS": "TR",
      "START": 1700,
      "END": 1815,
      "CLASSROOM": "W1104",
      "PER": 19,
      "CRDTS": 4,
      "LASTNAME": "Xu",
      "FIRSTNAME": "Yaquan"
    },
    {
      "CRN": 21784,
      "CRSE": "4800",
      "TITLE": "Internship in Service Learning",
      "SECT": 3,
      "DAYS": "TR",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "H1102",
      "PER": 17,
      "CRDTS": 3,
      "LASTNAME": "Jin/Xu",
      "FIRSTNAME": "Wei/Xin"
    },
    {
      "CRN": 21555,
      "CRSE": "4800",
      "TITLE": "Internship in Service Learning",
      "SECT": 1,
      "DAYS": "TR",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "B1275",
      "PER": 17,
      "CRDTS": 3,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 21779,
      "CRSE": "4800",
      "TITLE": "Internship in Service Learning",
      "SECT": 2,
      "DAYS": "MW",
      "START": 1230,
      "END": 1345,
      "CLASSROOM": "H1102",
      "PER": 5,
      "CRDTS": 3,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 21810,
      "CRSE": "4800",
      "TITLE": "Internship in Service Learning",
      "SECT": 4,
      "DAYS": "R",
      "START": 1100,
      "END": 1345,
      "CLASSROOM": "H2202",
      "PER": 16,
      "CRDTS": 3,
      "LASTNAME": "",
      "FIRSTNAME": ""
    },
    {
      "CRN": 20760,
      "CRSE": "4810",
      "TITLE": "Info Technology Project I",
      "SECT": 1,
      "DAYS": "F",
      "START": 1400,
      "END": 1645,
      "CLASSROOM": "B2100",
      "PER": 10,
      "CRDTS": 3,
      "LASTNAME": "Xu",
      "FIRSTNAME": "Shuting"
    },
    {
      "CRN": 21778,
      "CRSE": "4860",
      "TITLE": "Software Development Project",
      "SECT": 3,
      "DAYS": "T",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "A1900",
      "PER": 20,
      "CRDTS": 3,
      "LASTNAME": "Price",
      "FIRSTNAME": "Richard"
    },
    {
      "CRN": 22022,
      "CRSE": "4860",
      "TITLE": "Software Development Project",
      "SECT": 4,
      "DAYS": "R",
      "START": 1830,
      "END": 2115,
      "CLASSROOM": "A1400",
      "PER": 21,
      "CRDTS": 3,
      "LASTNAME": "Price",
      "FIRSTNAME": "Richard"
    },
    {
      "CRN": 20462,
      "CRSE": "4860",
      "TITLE": "Software Development Project",
      "SECT": 1,
      "DAYS": "MW",
      "START": 1700,
      "END": 1815,
      "CLASSROOM": "B2100",
      "PER": 9,
      "CRDTS": 3,
      "LASTNAME": "Im",
      "FIRSTNAME": "Tacksoo"
    },
    {
      "CRN": 20463,
      "CRSE": "4900",
      "TITLE": "Info Technology Internship",
      "SECT": 1,
      "DAYS": "F",
      "START": 800,
      "END": 850,
      "CLASSROOM": "H1102",
      "PER": 1,
      "CRDTS": 3,
      "LASTNAME": "Pollacia",
      "FIRSTNAME": "Lissa"
    }
  ];

  ngOnInit() {
  }

}
